version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  api:
    build: ./backend
    container_name: api
    ports:
      - 8000:8000
    environment:
      PORT: 8000
      MONGODB_URI: mongodb://mongo:27017
      DB_NAME: aja-db
    depends_on:
      - mongo
    networks:
      - app-network

  scripts:
    build:
      context: ./scripts
    container_name: scripts
    depends_on:
      - api
    networks:
      - app-network
    command: bash -c "python question.py &&python nonthema.py  && python molectoquest.py"

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
